---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-gitops-crds
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/brainfair/awesome-flux-crds.git
  ignore: |
    # exclude README.md
    /README.md
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-gitops-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-gitops-crds
