---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-gitops-istio-ratelimits
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/brainfair/istio-ratelimits.git
  ignore: |
    # exclude README.md
    /README.md
    LICENSE
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-gitops-istio-ratelimits
  namespace: flux-system
spec:
  dependsOn:
    - name: fluxcd-gitops-infra
  interval: 10m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-gitops-istio-ratelimits
  postBuild:
    substitute:
      env: "homelab"
      cluster_name: "docker-desktop"
      cluster_subdomain: "localhost.direct"
